allOf:
- $ref: https://json-schema.org/draft/2020-12/schema
- $ref: https://www.schemastore.org/jsonld.json
properties:
    class:
        type: array
    tags:
        type: array
        $comment: |
            tags are preferred over class because class is reserved in languages.
            this leaves us to avoid using reserved words generally.
    data:
        type: object
    item:
        type: object
    aria:
        type: object
    role:
        type: string
        dependentSchemas:
            unit:
                $ref: "#"
    attrs:
        title: element attributes
        type: object
    parent:
        title: define the parent outer parent of an element.
        $ref: '#'
    
