from .utils import el, parse_html

# the wai-aria roles are prototypes for the html respresentation.
# the role can be determined completely by a schema. once the role is determined,
# the html representation can be generated by the mapping.

def aria_labelledby(schema, object, options=None):
    aria = {"aria-labelledby": object.id("title")}
    description = object.description()
    if description:
        aria["aria-describedby"] = object.id("desc")
    return aria


def aria_role(schema, options=None):
    # the role may explicitly set in the schema
    role = schema.get("role")
    if role:
        return role
    enum = schema.get("enum")
    if enum:
        return "select"
        return "radiogroup"
    format = schema.get("format")
    if format:
        return "input"
    content = schema.get("contentMediaType")
    if content:
        return "code"
    t = schema.type()
    match t:
        case "array":
            return "list"
        case "object":
            return "associationlist"
        case "string":
            return "textbox"
        case "number" | "integer":
            return "spinbutton"
        case "boolean":
            return "checkbox"
        case _:
            return None
        
from .schemas import Schema, Object

Schema.role = aria_role

def html_attrs(schema, object, options=None, itemscope=False, **attrs):
    """convert a schema into html attributes for the object"""
    if itemscope:
        attrs.setdefault("item", {}).update(
            prop=object.path[-1]
        )
        if object.type() in ["object", "array"]:
            attrs["item"]["scope"] = ""
    if "attrs" in schema:
        attrs.update(schema["attrs"])
    if "on" in schema:
        for event, handler in schema["on"].items():
            attrs[f"on{event}"] = handler
    if "aria" in schema:
        for attribute, value in schema["aria"].items():
            if attribute not in {"expanded"}:
                attrs[f"aria-{attribute}"] = value
    if "data" in schema:
        for attribute, value in schema["data"].items():
            attrs[f"data-{attribute}"] = value
    if "item" in schema:
        for attribute, value in schema["item"].items():
            attrs[f"item{attribute}"] = value
    if "style" in schema:
        attrs["style"] = "; ".join(f"{k}: {v}" for k, v in schema["style"].items())
    # if "role" in schema:
    #     attrs["role"] = schema["role"]
    # if is_readonly(schema):
    #     attrs["readonly"] = ""

    attrs.setdefault("class", []).extend([str(object.path[-1]), object.type()])
    return attrs
    
def html_schema_applicator(schema, object, options, **attrs):
    """render keys in the applicator schema"""
    yield from html_schema_one_of(schema, object, options, **attrs)

def html_schema_one_of(schema, object, options, **attrs):
    one_of = schema.get("oneOf", [schema])
    for one in one_of:
        yield from html_schema_validator(one, object, options, **attrs)


    # yield from html_schema_if_then_else(schema, object, options, **attrs)

def html_schema_if_then_else(schema, object, options, **attrs):
    yield None

def html_schema_validator(schema, object, options, **attrs):
    role = aria_role(schema, object, options, **attrs)
    yield from role_mapping.get(role)(schema, object, options, **attrs)

def html_aria_list(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    type = schema.type() or object.type()
    if type == "array":
        items = enumerate(object)
    elif type == "object":
        items = object.items()
    else:
        raise ValueError(f"Cannot iterate over {type}")
    ol = el("ol", klass=[type], **attrs)
    for key, value in items:
        item = el("li.item", klass=[type, str(object.path[-1])], **attrs)
        link = el("a.item.anchor", str(), href="#" + value.id("anchor"), id=value.id("anchor"), **attrs)
        el(item, link)
        el(item, html_schema_applicator(value.schema, value, options))
    yield from role_mapping["group"](schema, object, options, ol)

def html_code(schema, object, options, **attrs):
    content = schema.get("contentMediaType")
    if content:
        f = content_mapping.get(content) or html_script
        yield from f(schema, object, options, **attrs)

def html_input(schema, object, options, **attrs):
    content = list(html_code(schema, object, options, **attrs))
    if content:
        yield from content
        return
    format = schema.get("format")
    if format:
        f = format_mapping.get(format)
        if f:
            yield from f(schema, object, options, **attrs)
            return
    type = schema.type() or object.type()
    match type:
        case "string":
            yield from html_input_string(schema, object, options, **attrs)
        case "number" | "integer":
            yield from html_input_number(schema, object, options, **attrs)
        case "boolean":
            yield from html_checkbox(schema, object, options, **attrs)
        case _:
            yield None

def html_select(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    select = el("select", klass=[object.type()])
    for value in schema.get("enum", []):
        attrs = {}
        if value == object:
            attrs["selected"] = ""
        # need something in the schema to rename the value
        option = el("option", str(value), value=value, **attrs)
        el(select, option)
    yield from html_label(schema, object, options)
    yield select

def html_input_string(schema, object, options, **attrs):
    if schema.get("aria", {}).get("multiline"):
        yield from html_textarea(schema, object, options, **attrs)
    else:
        attrs = html_attrs(schema, object, options, **attrs)
        attrs.update(aria_labelledby(schema, object, options))
        yield from html_label(schema, object, options)
        yield el("input", value=str(object), **attrs)

def html_textarea(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    yield from html_label(schema, object, options)
    body = str(object)
    attrs["rows"] = body.count("\n") + 1
    yield el("textarea", body, **attrs)

def html_checkbox(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    if object:
        attrs["checked"] = ""
    yield el("input", type="checkbox", value=str(object), **attrs)
    yield from html_label(schema, object, options)

def html_input_number(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    yield from html_label(schema, object, options)
    yield el("input", type="number", value=str(object), **attrs)

def html_datetime(schema, object, options, **attrs):
    attrs = html_attrs(schema, object, options, **attrs)
    attrs.update(aria_labelledby(schema, object, options))
    yield from html_label(schema, object, options)
    yield el("input", type="datetime-local", value=str(object), **attrs)

def html_label(schema, object, options, **attrs):
    yield el("label", str(object.title()), id=object.id("title"), **attrs)
    

def html_schema_format(schema, object, options, **attrs):
    yield None

def html_schema_content(schema, object, options, **attrs):
    yield None

def html_paragraph(schema, object, options, **attrs):
    yield el("p", str(object))

def html_script(schema, object, options, **attrs):
    super = Schema(schema, style=dict(display="block"))
    attrs = html_attrs(super, object, options, **attrs)
    yield el("script", str(object), type=schema.get("contentMediaType"), **attrs)

def html_from_string(schema, object, options, **attrs):
    """parse html from a string, returning a Tag or a list of Tags"""
    yield parse_html(object)

def html_markdown(schema, object, options, **attrs):
    """render markdown as html"""
    import markdown
    html = markdown.markdown(str(object))
    yield from html_from_string(schema, html, options, **attrs)

def html_json(schema, object, options, **attrs):
    """render json as html"""
    import json
    html = json.dumps(object, indent=2)
    yield from html_script(schema, html, options, **attrs)

role_mapping = dict(
    select=html_select,
    input=html_input,
    code=html_input,
    list=html_input,
    associationlist=html_input,
    textbox=html_input_string,
    spinbutton=html_input_number,
    checkbox=html_checkbox,
    paragraph=html_paragraph,
) | {None: html_paragraph}

format_mapping = dict(
    time=html_datetime
)

content_mapping = {
    "text/plain": html_script,
    "text/html": html_from_string,
    "text/markdown": html_markdown,
    "application/json": html_json
}